apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: us-central1-linkerd-external-demo.cloudfunctions.net
  namespace: demo
spec:
  routes:
  - name: '/slow'
    condition:
      pathRegex: '/slow'
      method: GET
    isRetryable: true